services:
  api:
    build:
      context: .
    container_name: surabank-api
    restart: always
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - redis
    networks:
      - apps-network

  redis:
    image: redis:7-alpine
    container_name: surabank-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    networks:
      - apps-network

volumes:
  redis_data:

networks:
  apps-network:
    external: true