name: Deploy

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd ~/apps/sura-api
          git pull origin main
          docker compose -f docker-compose.prod.yml up -d --build
